import React from "react";
import "./RecipePost.scss";

const RecipePost = () => {
  return (
    <div className="recipePost">
      <div className="container">
        <div className="left">
          <span className="breadcrumbs">KitchenGenie / Desserts </span>
          <h1>Italian Dishes & Desserts</h1>
          <div className="user">
            <img
              className="pp"
              src="../../../public/images/users/avatar-gen6ac8a09dcfed23747488bf2763420b5d.jpg"
              alt=""
            />
            <span>Uncle Roger</span>
            <div className="stars">
              <img src="/images/star.png" alt="" />
              <img src="/images/star.png" alt="" />
              <img src="/images/star.png" alt="" />
              <img src="/images/star.png" alt="" />
              <img src="/images/star.png" alt="" />
              <span>4</span>
            </div>
          </div>
          <img
            src="https://cdn.tasteatlas.com/images/dishes/468fa931d3004dd4b20f567cfb37c8b8.jpg?mw=1300"
            alt=""
          />
          <img
            src="https://cdn.tasteatlas.com/Images/Dishes/d382e315805b49a3afddbbf1232c8292.jpg?mw=1300"
            alt=""
          />
          <img
            src="https://cdn.tasteatlas.com/Images/Dishes/b7dc9c5b032742909193aab7bc660c80.jpg?mw=1300"
            alt=""
          />

          <h2>About This Recipe</h2>
          <p>
            You are probably wondering of how many orders for my recipes I've
            already got and delivered, you are worrying that I'm using AI to
            generate my recipe, and yes I do, even the text that you are reading
            now is generated by AI but rest assured that it is using my prompts
            aka my expertise and I do have to review the results and do the
            final refining before delivering to cover all of my clients
            requierements including, allergic and diet restrictions P.S: I'm an
            editor in a well known food magazine, I'm not Uber Eat, so cook the
            recipe yourself.
          </p>
          <div className="seller">
            <h2>About The Maker</h2>
            <div className="user">
              <img
                src="../../../public/images/users/avatar-gen6bb7f7feaa187f2d149ca24e73057fd7.jpg"
                alt=""
              />
              <div className="info">
                <span>Uncle Roger</span>
                <div className="stars">
                  <img src="/images/star.png" alt="" />
                  <img src="/images/star.png" alt="" />
                  <img src="/images/star.png" alt="" />
                  <img src="/images/star.png" alt="" />
                  <img src="/images/star.png" alt="" />
                  <span>4</span>
                </div>
                <button>Contact Me</button>
              </div>
            </div>
            <div className="box">
              <div className="items">
                <div className="item">
                  <span className="title">From</span>
                  <span className="desc">USA</span>
                </div>
                <div className="item">
                  <span className="title">Member since</span>
                  <span className="desc">Aug 2021</span>
                </div>
                <div className="item">
                  <span className="title">Avg. response time</span>
                  <span className="desc">2 hours</span>
                </div>
                <div className="item">
                  <span className="title">Last delivery</span>
                  <span className="desc">1 day</span>
                </div>
                <div className="item">
                  <span className="title">Languages</span>
                  <span className="desc">English</span>
                </div>
              </div>
              <hr />
              <p>
                My name is Uncle Roger, I enjoy creating recipes... (AI
                generated recipes also) in my spare time. I have a lot of
                experience in the kitchen and also now with AI with my unique
                prompts I can get a great and incredibly detailed results.
              </p>
            </div>
          </div>
          <div className="reviews">
            <h2>Reviews</h2>
            <div className="item">
              <div className="user">
                <img
                  className="pp"
                  src="../../../public/images/users/avatar-gen111a3a9182f84c1cb5336a5313b25602.jpg"
                  alt="user"
                />
                <div className="info">
                  <span> Fake Gordon Ramsey</span>
                  <div className="country">
                    <img src="https://flagsapi.com/GB/shiny/64.png" alt="" />
                    <span>United Kingdom</span>
                  </div>
                </div>
              </div>
              <div className="stars">
                <img src="/images/star.png" alt="" />
                <img src="/images/star.png" alt="" />
                <img src="/images/star.png" alt="" />
                <img src="/images/star.png" alt="" />
                <img src="/images/star.png" alt="" />
                <span>5</span>
              </div>
              <p>
                I loved this recipe here that you accepeted to tweek it for me
                since I cannot consumme any type of nuts. Communication was
                concise with quick response, each and every day he recipes that
                I was free to request changes to. he listened, understood, and
                delivered above and beyond my expectations. I absolutely
                recommend this recipe, and know already that Ill be cooking it
                again very very soon
              </p>
              <div className="helpful">
                <span>Helpful?</span>
                <img src="/images/like.png" alt="" />
                <span>Yes</span>
                <img src="/images/dislike.png" alt="" />
                <span>No</span>
              </div>
            </div>
            <hr />
            <div className="item">
              <div className="user">
                <img
                  className="pp"
                  src="../../../public/images/users/avatar-gen110d35a4071f2772aa3ddf905b3b5ff6.jpg"
                  alt=""
                />
                <div className="info">
                  <span>Oum Walid</span>
                  <div className="country">
                    <img
                      src="https://flagsapi.com/DZ/shiny/64.png"
                      alt="Not Oum Walid"
                    />
                    <span>Algeria</span>
                  </div>
                </div>
              </div>
              <div className="stars">
                <img src="/images/star.png" alt="" />
                <img src="/images/star.png" alt="" />
                <img src="/images/star.png" alt="" />
                <img src="/images/star.png" alt="" />
                <img src="/images/star.png" alt="" />
                <span>5</span>
              </div>
              <p>
                The recipe maker took my order in a minute, it is the next
                level! Professionalism and ease of working with Uncle Roger
                along with punctuality is above industry standards!! Whatever
                your needs they will be met with this guy!
              </p>
              <div className="helpful">
                <span>Helpful?</span>
                <img src="/images/like.png" alt="" />
                <span>Yes</span>
                <img src="/images/dislike.png" alt="" />
                <span>No</span>
              </div>
            </div>
            <hr />
            <div className="item">
              <div className="user">
                <img
                  className="pp"
                  src="../../../public/images/users/avatar-gen6ac8a09dcfed23747488bf2763420b5d.jpg"
                  alt=""
                />
                <div className="info">
                  <span>Giles from Top Tier Resto</span>
                  <div className="country">
                    <img src="https://flagsapi.com/DZ/shiny/64.png" alt="" />
                    <span>Algeria</span>
                  </div>
                </div>
              </div>
              <div className="stars">
                <img src="/images/star.png" alt="" />
                <img src="/images/star.png" alt="" />
                <img src="/images/star.png" alt="" />
                <img src="/images/star.png" alt="" />
                <img src="/images/star.png" alt="" />
                <span>5</span>
              </div>
              <p>
                Amazing work! Communication was amazing, and know already that
                I'll be back here again!
              </p>
              <div className="helpful">
                <span>Helpful?</span>
                <img src="/images/like.png" alt="" />
                <span>Yes</span>
                <img src="/images/dislike.png" alt="" />
                <span>No</span>
              </div>
            </div>
          </div>
        </div>
        <div className="right">
          <div className="price">
            <h3>1 Unique recipe</h3>
            <h2>$ 100.99</h2>
          </div>
          <p>
            I will create a unique high quality recipe based on a description
            that you give me
          </p>
          <div className="details">
            <div className="item">
              <img src="/images/clock.png" alt="" />
              <span>2 Days Delivery</span>
            </div>
            <div className="item">
              <img src="/images/recycle.png" alt="" />
              <span>3 Revisions</span>
            </div>
          </div>
          <div className="features">
            <div className="item">
              <img src="/images/greencheck.png" alt="" />
              <span>Recipe writing</span>
            </div>
            <div className="item">
              <img src="/images/greencheck.png" alt="" />
              <span>Recipe editing</span>
            </div>
            <div className="item">
              <img src="/images/greencheck.png" alt="" />
              <span>Additional details</span>
            </div>
            <div className="item">
              <img src="/images/greencheck.png" alt="" />
              <span>Consider dietary and medical conditions</span>
            </div>
          </div>
          <button>Continue</button>
        </div>
      </div>
    </div>
  );
};

export default RecipePost;
